import type { LoadedSkill } from './loader.js'

export const BUILTIN_SKILLS: LoadedSkill[] = [
  {
    id: 'snap',
    title: 'Snap Photo',
    path: 'builtin:snap',
    body: [
      '当用户想让你生成照片、合照、自拍感图片、把用户/你们放进某个场景，或用自然语言说“拍一张/生成一张/来张图”时，优先使用 `snap_photo` 工具。',
      '',
      '使用方式：',
      '- 从用户语境中整理出自然、具体的 `prompt`。',
      '- 调用 `snap_photo` 后，不要等待图片完成；用普通聊天语气告诉用户你已经在后台生成，完成后会放进“你的邮箱”，小信封会亮起。',
      '- 不要在回复中暴露内部 job id，除非用户明确询问。',
      '- 如果用户已经通过相机按钮附带了视觉快照，正常对话链路会携带它；`snap_photo` 仍只需要 `prompt`。',
    ].join('\n'),
  },
  {
    id: 'check-image-generation-progress',
    title: 'Check Image Generation Progress',
    path: 'builtin:check-image-generation-progress',
    body: [
      '当用户询问图片、照片、`/snap` 或 `snap_photo` 异步生成任务的进度、状态、失败原因或输出路径时使用。',
      '',
      '优先查看：',
      '- 队列/worker 生命周期日志：`.infiniti-agent/snap-async.log`',
      '- provider 请求和结果日志：`.infiniti-agent/snap.log`',
      '- job 文件：`.infiniti-agent/jobs/snap_*.json`',
      '- 邮箱结果：`.infiniti-agent/inbox/snap_*_{ok,failed}.json`',
      '- 图片资产：`.infiniti-agent/inbox/assets/infiniti-agent-snap-*`',
      '',
      '查询流程：',
      '1. 先看 `tail -n 80 .infiniti-agent/snap-async.log`，判断任务是否 enqueued / start / ok / failed。',
      '2. 若已 start 但没有邮箱结果，再看 `tail -n 120 .infiniti-agent/snap.log`，查 provider 错误、超时、下载失败或输出路径。',
      '3. 如果用户给了 job id，用 `rg "<job-id>" .infiniti-agent/snap-async.log .infiniti-agent/snap.log .infiniti-agent/inbox .infiniti-agent/jobs`。',
      '4. 只汇报最新状态：排队中、运行中、已完成并给出路径，或失败并给出关键错误。',
    ].join('\n'),
  },
  {
    id: 'check-video-generation-progress',
    title: 'Check Video Generation Progress',
    path: 'builtin:check-video-generation-progress',
    body: [
      '当用户询问 Seedance、视频、`/video`、`/seedance` 或 `seedance_video` 异步生成任务的进度、状态、失败原因、Ark task id 或输出路径时使用。',
      '',
      '优先查看：',
      '- 队列/worker 生命周期日志：`.infiniti-agent/video-async.log`',
      '- Seedance 请求、轮询和结果日志：`.infiniti-agent/seedance-video.log`',
      '- job 文件：`.infiniti-agent/jobs/video_*.json`',
      '- 邮箱结果：`.infiniti-agent/inbox/video_*_{ok,failed}.json`',
      '- 视频资产：`.infiniti-agent/inbox/assets/infiniti-agent-seedance-*`',
      '',
      '查询流程：',
      '1. 先看 `tail -n 80 .infiniti-agent/video-async.log`，判断任务是否 enqueued / start / ok / failed。',
      '2. 若已 start 但没有邮箱结果，再看 `tail -n 160 .infiniti-agent/seedance-video.log`，查 Ark task id、轮询状态、超时、API 错误或下载路径。',
      '3. 如果用户给了 job id 或 Ark task id，用 `rg "<job-or-task-id>" .infiniti-agent/video-async.log .infiniti-agent/seedance-video.log .infiniti-agent/inbox .infiniti-agent/jobs`。',
      '4. 只汇报最新状态：排队中、轮询/运行中、已完成并给出路径，或失败并给出关键错误。',
    ].join('\n'),
  },
]
