import type { LoadedSkill } from './loader.js'

export const BUILTIN_SKILLS: LoadedSkill[] = [
  {
    id: 'snap',
    title: 'Snap Photo',
    path: 'builtin:snap',
    body: [
      '当用户想让你生成照片、合照、自拍感图片、把用户/你们放进某个场景，或用自然语言说“拍一张/生成一张/来张图”时，优先使用 `snap_photo` 工具。',
      '',
      '使用方式：',
      '- 从用户语境中整理出自然、具体的 `prompt`。',
      '- 调用 `snap_photo` 后，不要等待图片完成；用普通聊天语气告诉用户你已经在后台生成，完成后会放进“你的邮箱”，小信封会亮起。',
      '- 不要在回复中暴露内部 job id，除非用户明确询问。',
      '- 如果用户已经通过相机按钮附带了视觉快照，正常对话链路会携带它；`snap_photo` 仍只需要 `prompt`。',
    ].join('\n'),
  },
  {
    id: 'check-image-generation-progress',
    title: 'Check Image Generation Progress',
    path: 'builtin:check-image-generation-progress',
    body: [
      '当用户询问图片、照片、`/snap` 或 `snap_photo` 异步生成任务的进度、状态、失败原因或输出路径时使用。',
      '',
      '优先查看：',
      '- 队列/worker 生命周期日志：`.infiniti-agent/snap-async.log`',
      '- provider 请求和结果日志：`.infiniti-agent/snap.log`',
      '- job 文件：`.infiniti-agent/jobs/snap_*.json`',
      '- 邮箱结果：`.infiniti-agent/inbox/snap_*_{ok,failed}.json`',
      '- 图片资产：`.infiniti-agent/inbox/assets/infiniti-agent-snap-*`',
      '',
      '查询流程：',
      '1. 先看 `tail -n 80 .infiniti-agent/snap-async.log`，判断任务是否 enqueued / start / ok / failed。',
      '2. 若已 start 但没有邮箱结果，再看 `tail -n 120 .infiniti-agent/snap.log`，查 provider 错误、超时、下载失败或输出路径。',
      '3. 如果用户给了 job id，用 `rg "<job-id>" .infiniti-agent/snap-async.log .infiniti-agent/snap.log .infiniti-agent/inbox .infiniti-agent/jobs`。',
      '4. 只汇报最新状态：排队中、运行中、已完成并给出路径，或失败并给出关键错误。',
    ].join('\n'),
  },
  {
    id: 'check-video-generation-progress',
    title: 'Check Video Generation Progress',
    path: 'builtin:check-video-generation-progress',
    body: [
      '当用户询问 Seedance、视频、`/video`、`/seedance` 或 `seedance_video` 异步生成任务的进度、状态、失败原因、Ark task id 或输出路径时使用。',
      '',
      '优先查看：',
      '- 队列/worker 生命周期日志：`.infiniti-agent/video-async.log`',
      '- Seedance 请求、轮询和结果日志：`.infiniti-agent/seedance-video.log`',
      '- job 文件：`.infiniti-agent/jobs/video_*.json`',
      '- 邮箱结果：`.infiniti-agent/inbox/video_*_{ok,failed}.json`',
      '- 视频资产：`.infiniti-agent/inbox/assets/infiniti-agent-seedance-*`',
      '',
      '查询流程：',
      '1. 先看 `tail -n 80 .infiniti-agent/video-async.log`，判断任务是否 enqueued / start / ok / failed。',
      '2. 若已 start 但没有邮箱结果，再看 `tail -n 160 .infiniti-agent/seedance-video.log`，查 Ark task id、轮询状态、超时、API 错误或下载路径。',
      '3. 如果用户给了 job id 或 Ark task id，用 `rg "<job-or-task-id>" .infiniti-agent/video-async.log .infiniti-agent/seedance-video.log .infiniti-agent/inbox .infiniti-agent/jobs`。',
      '4. 只汇报最新状态：排队中、轮询/运行中、已完成并给出路径，或失败并给出关键错误。',
    ].join('\n'),
  },
  {
    id: 'real2d-avatar-expression-set',
    title: 'Generate Real2D Avatar Expression Set',
    path: 'builtin:real2d-avatar-expression-set',
    body: [
      '当用户要求从一张透明头像/半身像生成 real2d 可识别的表情 PNG 套装，或提到 `exp01`…`exp06`、`exp_open`、real2d 表情素材时使用。',
      '',
      '调用方式：用户可以用自然语言请求，也可以用 `/avatargen <prompt>`。自然语言触发时，优先调用内置工具 `avatargen_real2d`，让任务异步入队并在完成/失败后写入邮箱。',
      '',
      '使用前必须检查 AvatarGen 设置。读取当前 `.infiniti-agent/config.json`（或实际加载的 config），只有 AvatarGen 的有效配置为 GPT-Image2 时才能继续：',
      '- `avatarGen.provider` 必须是 `chatgpt-image`。',
      '- `avatarGen.model` 必须是 `gpt-image-2`；如果 `provider` 已是 `chatgpt-image` 且未显式设置 `model`，按项目默认值视为 `gpt-image-2`。',
      '- 必须能解析到 OpenAI 图像 API Key：`avatarGen.apiKey`、`INFINITI_OPENAI_IMAGE_API_KEY`、`OPENAI_API_KEY`，或 OpenAI 默认 LLM profile 的 key。',
      '',
      '如果 AvatarGen 不是 GPT-Image2，直接提示用户：`当前 AvatarGen 不是 GPT-Image2 设置，real2d 表情集生成暂时不能使用。请把 avatarGen.provider 设为 chatgpt-image，并把 avatarGen.model 设为 gpt-image-2。` 不要改用 Nano Banana、Gemini、OpenRouter 或其它图像模型兜底。',
      '',
      '生成目标只包含 7 个 PNG 文件：',
      '- `exp01.png`：neutral，平静自然，闭口。',
      '- `exp02.png`：happy，开心微笑或明亮笑容。',
      '- `exp03.png`：sad，悲伤，嘴角下垂，无眼泪。',
      '- `exp04.png`：angry，皱眉、生气、紧张表情。',
      '- `exp05.png`：surprised，惊讶，睁大眼，轻微张口或 O 型嘴。',
      '- `exp06.png`：eyes_closed，平和闭眼，闭口。',
      '- `exp_open.png`：说话开口叠加图，自然张口，眼睛睁开，其余尽量中性。',
      '',
      '不要默认生成 `neutral.png`、`happy.png`、`sad.png`、`viseme_a.png`、`viseme_o.png`、`viseme_i.png`、`exp_a.png`、`exp_o.png`、`exp_ee.png` 或其它旧命名；real2d 默认只识别 `exp01.png`…`exp06.png` 和 `exp_open.png`。',
      '',
      '全局生成规则：始终使用用户提供的透明 PNG 作为最强身份参考；保持同一角色身份、发型、发色、肤色、服装、姿态、机位、裁切、比例、光照和分辨率；只改变指定表情或嘴型；输出必须是真 alpha 透明 PNG；不要添加背景、道具、文字、边框、阴影、场景或棋盘格。',
      '',
      '基础提示词模板：',
      '```text',
      'Using the provided transparent-background PNG avatar as the reference image, preserve the exact same character identity, hairstyle, outfit, body pose, camera angle, lighting, crop, scale, and transparent background.',
      '',
      'Modify only the facial expression or mouth shape according to the target description below.',
      '',
      'The output must be a PNG with a true alpha-transparent background. Do not create a white, black, gray, gradient, studio, or checkerboard background. Do not add props, text, shadows, scenery, borders, or extra objects. Keep the character centered and consistent with the source image.',
      '',
      'Target:',
      '{TARGET_PROMPT}',
      '```',
      '',
      '目标提示词：',
      '- `exp01.png`: `neutral calm expression, relaxed eyes, natural gaze, mouth closed, subtle relaxed lips, no strong emotion`',
      '- `exp02.png`: `happy cheerful expression, bright smile, smiling eyes, lifted cheeks, warm friendly look, same pose and framing`',
      '- `exp03.png`: `sad melancholy expression, downturned mouth corners, sad eyebrows raised at the inner ends, soft droopy eyes, quiet sorrowful look, no tears`',
      '- `exp04.png`: `angry expression, furrowed brows pointing downward toward the center, intense gaze, frowning or tight pressed lips, serious tense face`',
      '- `exp05.png`: `surprised expression, wide open eyes, eyebrows raised high, small open mouth or rounded surprised lips, alert startled look`',
      '- `exp06.png`: `eyes closed peacefully, relaxed expression, mouth closed, calm serene face, soft relaxed eyebrows, gentle peaceful mood`',
      '- `exp_open.png`: `natural speaking open mouth, jaw slightly lowered, lips parted in a clear talking shape, teeth slightly visible if natural, eyes open, otherwise neutral calm face`',
      '',
      '生成后检查：文件名必须精确匹配；每张图必须有真实 alpha；角色身份、服装、头发、头角度、身体位置、裁切和比例一致；`exp_open.png` 只能改变嘴部为自然说话开口；没有背景像素、文字或多余物。',
    ].join('\n'),
  },
]
